import { UserProfile, Session } from "./profile.types";

export const mockUserProfile: UserProfile = {
    id: "1",
    fullName: "Nabil Al-Rashidi",
    email: "nabil.rashidi@dez.gov.ae",
    phone: "+971 50 234 5678",
    location: "Dubai, UAE",
    department: "Operations Management",
    role: "Senior Manager",
    title: "Senior Manager · Operations Management",
    employeeId: "DEZ-2024-0087",
    memberSince: "March 15, 2022",
    accountStatus: "Active",
    avatarInitials: "NA",
    lastPasswordChange: 45,
};

export const mockSessions: Session[] = [
    {
        id: "1",
        deviceType: "Desktop",
        browser: "CHROME",
        deviceId: "A0DC563C...",
        ipAddress: "192.168.1.45",
        signedIn: "10 Jun 2026, 09:34",
        lastActive: "22m ago",
        expires: "17 Jun 2026, 09:34",
        status: "Current",
        isCurrent: true,
    },
    {
        id: "2",
        deviceType: "Mobile",
        browser: "SAFARI",
        deviceId: "B1ED674D...",
        ipAddress: "10.0.0.12",
        signedIn: "09 Jun 2026, 18:22",
        lastActive: "11h ago",
        expires: "16 Jun 2026, 18:22",
        status: "Active",
    },
    {
        id: "3",
        deviceType: "Desktop",
        browser: "FIREFOX",
        deviceId: "C2FE785E...",
        ipAddress: "172.16.254.3",
        signedIn: "08 Jun 2026, 13:10",
        lastActive: "1d ago",
        expires: "15 Jun 2026, 13:10",
        status: "Active",
    },
    {
        id: "4",
        deviceType: "Tablet",
        browser: "EDGE",
        deviceId: "D3GF896F...",
        ipAddress: "192.168.0.101",
        signedIn: "07 Jun 2026, 20:55",
        lastActive: "2d ago",
        expires: "14 Jun 2026, 20:55",
        status: "Active",
    },
    {
        id: "5",
        deviceType: "Desktop",
        browser: "CHROME",
        deviceId: "E4HG907G...",
        ipAddress: "::1",
        signedIn: "05 Jun 2026, 12:00",
        lastActive: "4d ago",
        expires: "12 Jun 2026, 12:00",
        status: "Active",
    },
];