/**
 * Canonical Cast of ~16 People
 * Specification: docs/DEMO-DATA-INTEGRATION.md Part 3
 *
 * Omar Al Hashmi is Line Manager; Fatima Al Marri is Section Head.
 * Layla Hassan is VENDOR-typed, assigned to Falcon Tech Resourcing.
 */

import { Person } from "./entities";

export const CAST: Record<string, Person> = {
  "usr-mariam": {
    id: "usr-mariam",
    name: "Mariam Al Mansoori",
    email: "mariam.almansoori@diez.ae",
    role: "Department Requestor",
    scope: "Digital Security, Data Management",
    departmentId: "dept-digital-security",
    departmentName: "Digital Security",
    userType: "INTERNAL",
    initials: "MM",
    title: "Senior Information Security Officer",
    avatarUrl: "/avatars/mariam.jpg",
  },
  "usr-ahmed-z": {
    id: "usr-ahmed-z",
    name: "Ahmed Al Zaabi",
    email: "ahmed.alzaabi@diez.ae",
    role: "Department Requestor",
    scope: "IT Infrastructure",
    departmentId: "dept-it-infra",
    departmentName: "IT Infrastructure",
    userType: "INTERNAL",
    initials: "AZ",
    title: "Lead Systems Engineer",
    avatarUrl: "/avatars/ahmed-z.jpg",
  },
  "usr-rashid-f": {
    id: "usr-rashid-f",
    name: "Rashid Al Falasi",
    email: "rashid.alfalasi@diez.ae",
    role: "Department Requestor",
    scope: "PMO",
    departmentId: "dept-pmo",
    departmentName: "PMO",
    userType: "INTERNAL",
    initials: "RF",
    title: "Senior Project Manager",
    avatarUrl: "/avatars/rashid-f.jpg",
  },
  "usr-hessa": {
    id: "usr-hessa",
    name: "Hessa Al Qassimi",
    email: "hessa.alqassimi@diez.ae",
    role: "Department Requestor",
    scope: "Finance",
    departmentId: "dept-finance",
    departmentName: "Finance",
    userType: "INTERNAL",
    initials: "HQ",
    title: "Financial Analyst",
    avatarUrl: "/avatars/hessa.jpg",
  },
  "usr-omar": {
    id: "usr-omar",
    name: "Omar Al Hashmi",
    email: "omar.alhashmi@diez.ae",
    role: "Line Manager",
    scope: "Digital Security",
    departmentId: "dept-digital-security",
    departmentName: "Digital Security",
    userType: "INTERNAL",
    initials: "OH",
    title: "Information Security Operations Manager",
    avatarUrl: "/avatars/omar.jpg",
  },
  "usr-fatima": {
    id: "usr-fatima",
    name: "Fatima Al Marri",
    email: "fatima.almarri@diez.ae",
    role: "Section Head",
    scope: "Digital Security",
    departmentId: "dept-digital-security",
    departmentName: "Digital Security",
    userType: "INTERNAL",
    initials: "FM",
    title: "Section Head - Cyber Defence",
    avatarUrl: "/avatars/fatima.jpg",
  },
  "usr-khalid": {
    id: "usr-khalid",
    name: "Khalid Al Suwaidi",
    email: "khalid.alsuwaidi@diez.ae",
    role: "Head of Department",
    scope: "Digital Security",
    departmentId: "dept-digital-security",
    departmentName: "Digital Security",
    userType: "INTERNAL",
    initials: "KS",
    title: "Head of Digital Security Department",
    avatarUrl: "/avatars/khalid.jpg",
  },
  "usr-youssef-b": {
    id: "usr-youssef-b",
    name: "Youssef Al Blooshi",
    email: "youssef.alblooshi@diez.ae",
    role: "Head of Department",
    scope: "PMO (no Section Head in this chain)",
    departmentId: "dept-pmo",
    departmentName: "PMO",
    userType: "INTERNAL",
    initials: "YB",
    title: "Director of Enterprise PMO",
    avatarUrl: "/avatars/youssef-b.jpg",
  },
  "usr-mona": {
    id: "usr-mona",
    name: "Mona Al Shamsi",
    email: "mona.alshamsi@diez.ae",
    role: "Head of Department",
    scope: "IT Infrastructure (no Section Head)",
    departmentId: "dept-it-infra",
    departmentName: "IT Infrastructure",
    userType: "INTERNAL",
    initials: "MS",
    title: "Head of IT Infrastructure Department",
    avatarUrl: "/avatars/mona.jpg",
  },
  "usr-aisha": {
    id: "usr-aisha",
    name: "Aisha Al Nuaimi",
    email: "aisha.alnuaimi@diez.ae",
    role: "HR Specialist",
    scope: "Organisation-wide",
    departmentId: "dept-hr",
    departmentName: "HR",
    userType: "INTERNAL",
    initials: "AN",
    title: "Senior HR Business Partner & Workforce Specialist",
    avatarUrl: "/avatars/aisha.jpg",
  },
  "usr-rashid-m": {
    id: "usr-rashid-m",
    name: "Rashid Al Mansoori",
    email: "rashid.almansoori@diez.ae",
    role: "Finance Manager",
    scope: "Organisation-wide",
    departmentId: "dept-finance",
    departmentName: "Finance",
    userType: "INTERNAL",
    initials: "RM",
    title: "Finance Operations & Budget Manager",
    avatarUrl: "/avatars/rashid-m.jpg",
  },
  "usr-salma": {
    id: "usr-salma",
    name: "Salma Al Ketbi",
    email: "salma.alketbi@diez.ae",
    role: "Procurement Officer",
    scope: "Organisation-wide",
    departmentId: "dept-procurement",
    departmentName: "Procurement",
    userType: "INTERNAL",
    initials: "SK",
    title: "Senior Procurement Officer",
    avatarUrl: "/avatars/salma.jpg",
  },
  "usr-noura": {
    id: "usr-noura",
    name: "Noura Al Mazrouei",
    email: "noura.almazrouei@diez.ae",
    role: "Main Interviewer",
    scope: "Digital Security, Data Management",
    departmentId: "dept-digital-security",
    departmentName: "Digital Security",
    userType: "INTERNAL",
    initials: "NA",
    title: "Lead Security Architect",
    avatarUrl: "/avatars/noura.jpg",
  },
  "usr-yousef-f": {
    id: "usr-yousef-f",
    name: "Yousef Al Falasi",
    email: "yousef.alfalasi@diez.ae",
    role: "Panel Interviewer",
    scope: "Digital Security",
    departmentId: "dept-digital-security",
    departmentName: "Digital Security",
    userType: "INTERNAL",
    initials: "YF",
    title: "Senior SOC Analyst",
    avatarUrl: "/avatars/yousef-f.jpg",
  },
  "usr-layla": {
    id: "usr-layla",
    name: "Layla Hassan",
    email: "layla.hassan@falcontech.ae",
    role: "Vendor Coordinator",
    scope: "Vendor: Falcon Tech Resourcing",
    departmentId: "dept-vendor-falcon",
    departmentName: "Falcon Tech Resourcing",
    userType: "VENDOR",
    vendorId: "ven-falcon",
    initials: "LH",
    title: "Senior Account Coordinator",
    avatarUrl: "/avatars/layla.jpg",
  },
  "usr-admin": {
    id: "usr-admin",
    name: "Ahmed Al Dhaheri",
    email: "ahmed.aldhaheri@diez.ae",
    role: "System Administrator",
    scope: "Global",
    departmentId: "dept-it-infra",
    departmentName: "IT Infrastructure",
    userType: "INTERNAL",
    initials: "AD",
    title: "Enterprise Systems Administrator",
    avatarUrl: "/avatars/admin.jpg",
  },
};

/**
 * Secondary alias mappings for backwards compatibility with earlier fixtures
 */
export const USER_ALIASES: Record<string, string> = {
  "usr-omar-01": "usr-omar",
  "usr-091": "usr-noura",
  "usr-104": "usr-yousef-f",
  "usr-118": "usr-omar",
  "usr-hr-042": "usr-aisha",
  "u-101": "usr-khalid",
  "u-102": "usr-fatima",
  "u-103": "usr-omar",
  "u-104": "usr-aisha",
  "u-105": "usr-yousef-f",
};

export const CAST_LIST: Person[] = Object.values(CAST);
